
ticketpanel:
  enabled: true 
  permissions: ["*"]
  aliases: ["tpanel"]

rolepanel:
  enabled: true 
  permissions: ["*"]
  aliases: ["rpanel"]

ban:
  enabled: true 
  permissions: ["*"]
  aliases: ["banish"]

kick:
  enabled: true 
  permissions: ["*"]
  aliases: ["bye"]

mute:
  enabled: true 
  permissions: ["*"]
  aliases: ["silence", "stfu"]

unban:
  enabled: true 
  permissions: ["*"]
  aliases: ["uban"]

slowmode:
  enabled: true 
  permissions: ["*"]
  aliases: ["sm"]

promote:
  enabled: true 
  permissions: ["*"]
  aliases: []

assign:
  enabled: true 
  permissions: ["*"]
  aliases: ["giverole", "grole", "addrole", "arole"]

unassign:
  enabled: true 
  permissions: ["*"]
  aliases: ["takerole", "trole", "removerole", "rrole"]

serverinfo:
  enabled: true 
  permissions: ["@everyone"]
  aliases: ["sinfo"]

verify:
  enabled: true
  permissions: ["@everyone"]
  aliases: []

bundleadd:
  enabled: true
  permissions: ["*"]
  aliases: ["bunadd", "badd"]

bundleremove:
  enabled: true
  permissions: ["*"]
  aliases: ["bunremove", "bremove"]

bundlequeue:
  enabled: true
  permissions: ["*"]
  aliases: ["bunqueue", "bqueue"]

bundlefinished:
  enabled: true
  permissions: ["*"]
  aliases: ["bunfinished", "bfinished", "bdone", "bundone", "bunlist", "blist"]

bundlegiven:
  enabled: true
  permissions: ["*"]
  aliases: ["bungiven", "bgiven", "bungive", "bgive"]

bundletaken:
  enabled: true
  permissions: ["*"]
  aliases: ["buntaken", "btaken", "buntake", "btake"]

embed:
  enabled: true
  permissions: ["*", "test12345"]
  aliases: ["say"]

avatar:
  enabled: true
  permissions: ["@everyone"]
  aliases: ["profilepic", "pic", "picture"]

invites:
  enabled: true 
  permissions: ["@everyone"]
  aliases: []

invite:
  enabled: true 
  permissions: ["@everyone"]
  aliases: []

invitetop:
  enabled: true
  permissions: ["@everyone"]
  aliases: []

test:
  enabled: true
  permissions: ["@everyone"]
  aliases: []

ticketlog:
  enabled: true
  permissions: ["*"]
  aliases: ["tlog"]

ticketdelete:
  enabled: true
  permissions: ["*"]
  aliases: ["tdelete"]

ticketstats:
  enabled: true
  permissions: ['@everyone']
  aliases: ["tstats"]

messagesstats:
  enabled: true
  permissions: ['@everyone']
  aliases: ['mstats']

suggest:
  enabled: true
  permissions: ['@everyone']
  aliases: []

ticketclose:
  enabled: true
  permissions: ['@everyone']
  aliases: ['close', 'tclose']

ticketadd:
  enabled: true
  permissions: ['*']
  aliases: ['tadd']

ticketremove:
  enabled: true
  permissions: ['*']
  aliases: ['tremove']

purge:
  enabled: true
  permissions: ['*']
  aliases: []

helppanel:
  enabled: true
  permissions: ["@everyone"]
  aliases: ["help"]

pollcreate:
  enabled: true
  permissions: ["*"]
  aliases: ["createpoll", "cpoll", "pcreate"]

pollend:
  enabled: true
  permissions: ["*"]
  aliases: ["endpoll", "epoll", "pend"]

pollvoters:
  enabled: true
  permissions: ["*"]
  aliases: ["voterspoll", "vpoll", "pvoters"]

pollinfo:
  enabled: true
  permissions: ["*"]
  aliases: ["infopoll", "ipoll", "pinfo"]