  ###################
  # Ticket Category #
  ###################


ticketinfo:
  enabled: true
  permissions: ['@everyone']
  aliases: ['tinfo']

ticketclose:
  enabled: true
  permissions: ['@everyone']
  aliases: ['close', 'tclose']

ticketadd:
  enabled: true
  permissions: ['*']
  aliases: ['tadd']

ticketremove:
  enabled: true
  permissions: ['*']
  aliases: ['tremove']

ticketlog:
  enabled: true
  permissions: ["*"]
  aliases: ["tlog"]

ticketdelete:
  enabled: true
  permissions: ["*"]
  aliases: ["tdelete"]

ticketstats:
  enabled: true
  permissions: ['@everyone']
  aliases: ["tstats"]


  #######################
  # Moderation Category #
  #######################

purge:
  enabled: true
  permissions: ['*']
  aliases: []
  
ban:
  enabled: true 
  permissions: ["*"]
  aliases: ["banish"]

kick:
  enabled: true 
  permissions: ["*"]
  aliases: ["bye"]

mute:
  enabled: true 
  permissions: ["*"]
  aliases: ["silence", "stfu"]

unban:
  enabled: true 
  permissions: ["*"]
  aliases: ["uban"]

slowmode:
  enabled: true 
  permissions: ["*"]
  aliases: ["sm"]

promote:
  enabled: true 
  permissions: ["*"]
  aliases: []

demote:
  enabled: true 
  permissions: ["*"]
  aliases: []

assign:
  enabled: true 
  permissions: ["*"]
  aliases: ["giverole", "grole", "addrole", "arole"]

unassign:
  enabled: true 
  permissions: ["*"]
  aliases: ["takerole", "trole", "removerole", "rrole"]


  ###################
  # Poll Category #
  ###################


pollcreate:
  enabled: true
  permissions: ["*"]
  aliases: ["createpoll", "cpoll", "pcreate"]

pollend:
  enabled: true
  permissions: ["*"]
  aliases: ["endpoll", "epoll", "pend"]

pollvoters:
  enabled: true
  permissions: ["*"]
  aliases: ["voterspoll", "vpoll", "pvoters"]

pollinfo:
  enabled: true
  permissions: ["*"]
  aliases: ["infopoll", "ipoll", "pinfo"]


  ###################
  # Bundle Category #
  ###################

bundleadd:
  enabled: true
  permissions: ["*"]
  aliases: ["bunadd", "badd"]

bundleremove:
  enabled: true
  permissions: ["*"]
  aliases: ["bunremove", "bremove"]

bundlequeue:
  enabled: true
  permissions: ["*"]
  aliases: ["bunqueue", "bqueue"]

bundlefinished:
  enabled: true
  permissions: ["*"]
  aliases: ["bunfinished", "bfinished", "bdone", "bundone", "bunlist", "blist"]

bundlegiven:
  enabled: true
  permissions: ["*"]
  aliases: ["bungiven", "bgiven", "bungive", "bgive"]

bundletaken:
  enabled: true
  permissions: ["*"]
  aliases: ["buntaken", "btaken", "buntake", "btake"]

  #################
  # Info Category #
  #################

serverinfo:
  enabled: true 
  permissions: ["@everyone"]
  aliases: ["sinfo"]

avatar:
  enabled: true
  permissions: ["@everyone"]
  aliases: ["profilepic", "pic", "picture"]

invites:
  enabled: true 
  permissions: ["@everyone"]
  aliases: []

invite:
  enabled: true 
  permissions: ["@everyone"]
  aliases: []

invitetop:
  enabled: true
  permissions: ["@everyone"]
  aliases: []
  
messagesstats:
  enabled: true
  permissions: ['@everyone']
  aliases: ['mstats']

  ###################
  # Utils Category #
  ###################


ticketpanel:
  enabled: true 
  permissions: ["*"]
  aliases: ["tpanel"]

applicationpanel:
  enabled: true 
  permissions: ["*"]
  aliases: ["apanel"]

rolepanel:
  enabled: true 
  permissions: ["*"]
  aliases: ["rpanel"]

verify:
  enabled: true
  permissions: ["@everyone"]
  aliases: []

embed:
  enabled: true
  permissions: ["*", "test12345"]
  aliases: ['say']

editembed:
  enabled: true
  permissions: ["*", "test12345"]
  aliases: ['editsay']

suggest:
  enabled: true
  permissions: ['@everyone']
  aliases: []

helppanel:
  enabled: true
  permissions: ["@everyone"]
  aliases: ["help"]

afk:
  enabled: true
  permissions: ["@everyone"]
  aliases: ["gone"]

  #####################
  # Giveaway Category #
  #####################


giveawaycreate:
  enabled: true
  permissions: ["*"]
  aliases: ["creategiveaway", "cgiveaway", "gcreate"]

giveawayend:
  enabled: true
  permissions: ["*"]
  aliases: ["endgiveaway", "egiveaway", "gend"]

giveawayinfo:
  enabled: true
  permissions: ["*"]
  aliases: ["infogiveaway", "igiveaway", "ginfo"]

giveawayentries:
  enabled: true
  permissions: ["*"]
  aliases: ["gentries", "engiveaway", "entriesgiveaway"]

giveawayreroll:
  enabled: true
  permissions: ["*"]
  aliases: ["rerollgiveaway", "rgiveaway", "greroll"]

  #####################
  # Fun Category #
  #####################

minesweeper:
  enabled: true
  permissions: ["@everyone"]
  aliases: []

tictactoe:
  enabled: true
  permissions: ["@everyone"]
  aliases: []

rockpaperscissors:
  enabled: true
  permissions: ["@everyone"]
  aliases: ["rps"]

  #####################
  # Level Category #
  #####################

level:
  enabled: true
  permissions: ["@everyone"]
  aliases: []
  
leveltop:
  enabled: true
  permissions: ["@everyone"]
  aliases: []
