minecraft:
  bot: 
    server_ip: "" 
    username: ""  
    password: "" 
    auth: "" 

discord:
  bot:
    token: "NzcxMTc0NDQ4NzU3NjA0Mzcy.X5oSLA.xmPfrgbn4cMDW7Ip1qlW44UB_a4"
    prefix: ";"
    cooldown: "5" 
    admin_users:
      - "804462623768707103"